services:

  app:
    image: node:18-alpine
    command: sh -c "npm install && npm run build && npm run start"
    ports:
      - ${APP_PORT}:3000
    working_dir: /app
    volumes:
      - ./flapp_app:/app
    environment:
      - NEXT_PUBLIC_API_URL=${APP_NEXT_PUBLIC_API_URL}

  api:
    image: node:18-alpine
    command: sh -c "npm install && npm run build && npm run start"
    ports:
      - ${API_PORT}:3001
    working_dir: /api
    volumes:
      - ./flapp_api:/api
    environment:
      - TRAELO_YA_API_KEY=${API_TRAELO_YA_API_KEY}
      - UDER_API_KEY=${API_UDER_API_KEY}
